theme: jekyll-theme-cayman
title: Cisco UCS Developer Resources
description: UCS is the ultimate platform for DevOps, Containers, and Programmability.<br>Here we give you the resources to know how to make it happen with the tools you already love. 
